FROM python:3.11-slim

WORKDIR /app

COPY requirements-torch.txt .
RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements-torch.txt

COPY train_torch.py .

CMD ["python", "train_torch.py"]
