services:
  nn-numpy:
    build:
      context: .
      dockerfile: Dockerfile
    image: nn-x2-test:latest
    environment:
      - NOISE_STD=${NOISE_STD:-0.03}
      - NUM_OBS=${NUM_OBS:-4}
    volumes:
      - results-volume:/app/out

  nn-torch:
    profiles:
      - torch
    build:
      context: .
      dockerfile: Dockerfile.torch
    image: nn-x2-torch-test:latest
    environment:
      - NOISE_STD=${NOISE_STD:-0.03}
      - NUM_OBS=${NUM_OBS:-4}
    volumes:
      - results-volume:/app/out

volumes:
  results-volume:
    external: true
    name: ${RESULTS_VOLUME:-DockerVolume}
